service: py-fastapi-service

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:603684165690:table/products-table
        - arn:aws:dynamodb:us-east-1:603684165690:table/products-table/index/TypeIndex

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /products
          method: ANY
          cors: true
      - http:
          path: /products/type/{product_type}
          method: get
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
